### ISSUE TITLE
Compiling JSON Schema draft-03

### ISSUE THREAD

**Issue by Koka5** [zaggino/z-schema#100]
I have a few draft -03 json schema for some js objects.
I am setting remote references with the help of its api setRemoteReference and providing the draft-03 schema object from here http://json-schema.org/draft-03/schema#

var ZSV = new ZSchemaValidator({ breakOnFirstError: false });
ZSV.setRemoteReference('http://json-schema.org/draft-03/schema#', {
  // json object downloaded from draft-03 url
});

But i call validate method it throws error

[{"code":"REMOTE_NOT_VALID","params":["http://json-schema.org/draft-03/schema#"],"message":"Remote reference didn't compile successfully: http://json-schema.org/draft-03/schema#","path":"#/uri(http://json-schema.org/draft-03/schema)","inner":  ....
Seems like the compilation failed.

But how come the schema object downloaded from authentic source http://json-schema.org/draft-03/schema# can be wrong.?

Or is it that, z-schema not able to compile draft-03 effectively.?

So my question is, how can i validate draft-03 using z-schema?

**Comment by zaggino** [comment]
Hi @Koka5 , z-schema was never coded or tested with draft3, it supports only draft4 right now.

**Comment by Koka5** [comment]
Is there any workaround for the same?

**Comment by zaggino** [comment]
Probably not, there're other validators that support v3. And I think I've seen a tool that converts v3 schemas to v4 but I'm not sure where.
