### ISSUE TITLE
Cannot read property '__$compiled' of undefined

### ISSUE THREAD

**Issue by simon-p-r** [zaggino/z-schema#101]
Hi

I am trying to test z-schema as part of a module I am writing and I keep getting this error when running the validate method asynchronously.  

Thanks
Simon

**Comment by zaggino** [comment]
Can you post the full-stack or at least the line which throws this error?

**Comment by simon-p-r** [comment]
Cannot read property '__$compiled' of undefined

      at ZSchema.exports.compileSchema (D:\modules\aim-schema\node_modules\z-schema\src\SchemaCompilation.js:193:15)
      at ZSchema.validate (D:\modules\aim-schema\node_modules\z-schema\src\ZSchema.js:123:52)
      at internals.Manager.validateData (D:\modules\aim-schema\lib\manager.js:286:85)
      at D:\modules\aim-schema\test\validate.js:69:11
      at Immediate._onImmediate (D:\modules\aim-schema\node_modules\lab\lib\runner.js:445:17)
      at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by zaggino** [comment]
Can you try again with version `3.9.2` ?

**Comment by simon-p-r** [comment]
D:\modules\aim-schema>npm test

> aim-schema@2.0.0 test D:\modules\aim-schema
> lab -a code -v -L -t 100

Formats
  V 1) should validate phone numbers (53 ms)
  V 2) should validate post codes (0 ms)
  V 3) should validate object id (12 ms)
Manager
  V 4) should throw an error constructed without new (2 ms)
  V 5) should throw an error when not passed an options object to constructor (11 ms)
  V 6) should create a settings object via hoek, applying defaults to object passed to constructor (63 ms)
16 schemas successfully compiled
  V 7) should create a settings object via hoek, applying defaults to object passed to constructor (38 ms)
  V 8) should serialize and deserialize a function (31 ms)
  V 9) should throw on joi validation (39 ms)
  V 10) should serialize an object to json sting (28 ms)
16 schemas successfully compiled
Validator
  V 11) should validate data against schema sync (34 ms)
16 schemas successfully compiled
  ×12) should validate data against schema async


Failed tests:

  12) Validator should validate data against schema async:

      undefined is not a function

      at D:\modules\aim-schema\lib\manager.js:289:72
      at D:\modules\aim-schema\node_modules\z-schema\src\ZSchema.js:124:17
      at process._tickDomainCallback (node.js:381:11)


1 of 12 tests failed
Test duration: 375 ms
Assertions count: 25 (verbosity: 2.08)
No global variable leaks detected
Coverage: 84.15% (68/429)
lib/manager.js missing coverage on line(s): 136, 137, 138, 152, 157, 158, 160, 161, 163, 165, 166, 168, 171, 172, 173, 175, 176, 178, 185, 189, 193, 194, 195, 199, 204, 205, 206, 208, 209, 211, 214, 216, 217, 218, 220, 221, 223, 226, 227, 229, 236, 240, 244, 263, 271, 272, 274, 278, 287, 290, 291, 2
92, 294, 296, 298, 300
lib/schema.js missing coverage on line(s): 15
lib/formats/postcode.js missing coverage on line(s): 71, 72
lib/formats/telephone.js missing coverage on line(s): 45, 46, 47, 66, 67, 68, 74, 75, 76
Code coverage below threshold: 84.15 < 100

npm ERR! Test failed.  See above for more details.

**Comment by zaggino** [comment]
Check the line which errors `ZSchema.js:124:17` - https://github.com/zaggino/z-schema/blob/master/src/ZSchema.js#L119-L124
You're passing `undefined` instead of the actual schema

**Comment by zaggino** [comment]
And current fail `undefined is not a function` happens in your code: `at D:\modules\aim-schema\lib\manager.js:289:72`

**Comment by simon-p-r** [comment]
Thanks fixed, sorry this is my first real use of testing so still getting use to it.

**Comment by zaggino** [comment]
:+1:
