### ISSUE TITLE
Register format input check

### ISSUE THREAD

**Issue by simon-p-r** [zaggino/z-schema#108]
Hi Martin

I can't see where the function registered is type checked, for example I am writing this code to check input to a register format function but cannot follow very well during debug!

````JS

dbRef: function (obj, callback) {

		if (!obj || typeof obj !== 'object') {
			return callback(false);
		}

		var query = {};

		if (oid.isOID(obj.q)) {
			query = {_id: obj.q};
		} else {
			query = obj.q;
		}

		var collection = this.db.collection(obj.cn);
		collection.findOne(query, function (err, rec) {

			if (err) {
				return callback(false);
			}
			if (!rec) {
				return callback(false);
			}
			return callback(true);
		});

	},

````

Thanks
Simon

**Comment by zaggino** [comment]
That'd be here: https://github.com/zaggino/z-schema/blob/master/src/JsonValidation.js#L310-L330
Async tasks are executed once all the sync validation is finished.

**Comment by simon-p-r** [comment]
Excellent I have manage to reduce some lines of code now I know what you are computing under the hood?  

Thanks
Simon
