### ISSUE TITLE
CLI: Implement exit code

### ISSUE THREAD

**Issue by Kegsay** [zaggino/z-schema#109]
It would be great if `z-schema` returned a non-zero exit code if a validation failed. I'm currently using it in a shell script but have to parse stdout :(
```
 $ z-schema schema.json example.json
schema validation passed
[
    {
        "code": "ENUM_MISMATCH",
        "params": [
            "name"
        ],
        "message": "No enum match for: name",
        "path": "#/type"
    }
]
json #1 validation failed

 $ echo $?
0
```

**Comment by zaggino** [comment]
Should be fixed in version 3.10.1

**Comment by Kegsay** [comment]
This is great, thanks, but it only works in Node.js `0.12.*` and not `0.10.*` as per https://github.com/joyent/node/issues/8557 - If you want to preserve compatibility could you please use `process.exit(1)` instead (and possibly storing the exit code so all validations run if you don't want to fail fast)?

**Comment by zaggino** [comment]
Ah, didn't know that. Can you try if `3.10.2` is ok?

**Comment by Kegsay** [comment]
`3.10.2` works great, thank you!

**Comment by zaggino** [comment]
:+1:
