### ISSUE TITLE
Support for custom validators.

### ISSUE THREAD

**Issue by IvanGoncharov** [zaggino/z-schema#114]
For many use cases JSON Schema isn't enough to check all restrictions.
So right now, typical scenario is validate using JSON schema validator and them use hand-write recursive code.

 Consider following schema:
```json
{
   "definitions": {
       "TestType": {
          "type": "string",
          "description": "Type that should be additionally validated"
       }
   },
   "oneOf" : [
      { "$ref": "#/definitions/TestType" },
      {
        "type": "array",
        "items": { "$ref": "#/definitions/TestType" }
      }
   ]
}
```
So JS validation code would be, like that:
```javascript
function validate(data) {
  if (data.constructor === Array) {
    for (var i = 0; i < data.lenght; i++)
       validateTestType(data);
    return;
  }
  validateTestType(data);
}

function validateTestType(data) {
  //user specific validation
}
```
In real life hand-written validator quickly mirror most of JSON Schema.
It especially hard to work with 'oneOf', 'allOf', etc.
My idea is to allow user to specify additional validators for JSON Schema types.
Syntax could be like following:
```javascript
var valid = validator.validate(json, schema, {
  "#/definitions/TestType": function (report, json) {
     //user specific validation
  }
});
```
It not only simplify code but also significantly improve speed of full validation.
In next couple of days I could prepare PR.
What do you think about such functionality?

**Comment by zaggino** [comment]
how does this differ from using a `format` keyword and a custom format? i'm not sure I understand what you're trying to do

**Comment by IvanGoncharov** [comment]
You right, in theory it could be handled by custom `format` keywords.
In reality where are several problem:
- You need to add unique format keywords to almost all types.
- It could result in name clash if you reference external schemas
- In many cases you can't modify JSON Schema.

IMHO, custom formats should be used for clearly defined repetitive validations, like IP or MAC address, etc. In case there you using it for unique validations, you basically transform `format` into `id`.

In my first post I tried to create minimal example to illustrate problem.
Probably it would be better to fully describe my use-case.
I'm trying to validate [Swagger](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) documents, they have JSON [schema](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json) for validation.
But schema validate only half of [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) requirements.

Let's see how it handled in existing libraries, for example [swagger-parser](https://github.com/BigstickCarpet/swagger-parser) lib
Typical solution is to [validate using schema](https://github.com/BigstickCarpet/swagger-parser/blob/master/lib/validate.js#L44) as first step and then traverse entire JSON second time to do [custom validation](https://github.com/BigstickCarpet/swagger-parser/blob/master/lib/validate.js#L58)(rest of the file).

These approach not only inefficient(you traverse JSON twice) but also error-prone.
For example in above mentioned library, author forget that one of type could be used in multiply places and validate it only in most obvious place.

Proposed solution have the following benefits:
- JSON traversed only once
- Validation bind to type, `z-shema` detect type usage and call validator
- Programmer shouldn't traverse complicated construction like `allOf`, `oneOf`, `anyOf`.

It's problem less critical for not so complex validation scenarios.
But I think all schemas above couple of hundreds lines will produce the same exact problem.

**Comment by zaggino** [comment]
Ok, cool ... convinced ... if you can implement this with tests, I'll be happy to merge and release it.

**Comment by epoberezkin** [comment]
That's quite common request. There are several problems with that approach though:

1. It does not scale across multiple platforms. Custom keywords that find their way into schemas will not be handled in the same way in platforms written in other languages (or not handled at all). So JSON schemas lose one of its main advantages - platform independence.
2. The desire to use custom keywords is often caused by the lack of knowledge of what JSON schemas support. `patternProperties` and `dependencies` cover substantial part of the situations where some developers try to use imperative validation (as opposed to declarative).
3. Same desire is often an indication of bad data design. Often making data structures less coupled and dependent on each other removes the need in imperative validation.

I think that while JSON-schema validators can easily be extended to support custom keywords and functional hooks, they should not do it with the exception of format keyword for string validation.

There are indeed some data requirements that cannot be expressed in JSON schema. I believe that such requirements should not be expressed by extending JSON schemas. Rarely if ever such requirements would live inside `anyOf` keyword.

I am happy to look at specific example of data validation scenario that cannot be expressed via JSON schema to try to suggest some solution.

**Comment by IvanGoncharov** [comment]
@epoberezkin Very simple example ID field. I need to check that it have unique values in whole document. 
Next one, I validate format which use JSON Schema internally, so I want to  validate it using [this](https://github.com/zaggino/z-schema/blob/master/src/SchemaValidation.js#L512) function.

JSON Schema document themselves  couldn't  be validate only with schema, for example #112
In my use case I working with very complex [schema](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json) and [this](https://github.com/apigee-127/sway/blob/master/docs/versions/2.0.md) list show things that can't be validated using JSON Schema.

I agree with you that in most cases people simply don't know JSON Schema.
But at the same time, you shouldn't limit experience users.
If you need to do many additional checks in different parts of JSON document, you end up traversing whole document so you loose all benefits of JSON Schema.

**Comment by IvanGoncharov** [comment]
I really want to implement this feature, but right now I stuck with my current work :disappointed: 
I would try to find some time in next couple of months, but it would great if someone create PR before that.

**Comment by epoberezkin** [comment]
> Very simple example ID field. I need to check that it have unique values in whole document.

Indeed, it can't be and probably shouldn't be validated with JSON-schema. JSON-schema describes structure/format/values range validity. Semantic validity is out of its scope.

> Next one, I validate format which use JSON Schema internally, so I want to validate it using this function.
> JSON Schema document themselves couldn't be validate only with schema, for example #112
In my use case I working with very complex schema and this list show things that can't be validated using JSON Schema.

I disagree. The fact that "default" keyword has value that is invalid according to the schema doesn't make the schema invalid. Standard only recommends that it is valid according to the schema, it doesn't require it (see http://json-schema.org/latest/json-schema-validation.html#anchor103). Same about "enum". JSON-Schema can easily be written in such way that there will be no JSON document that is valid according to such schema. The attempt to validate "default" and "enum" is an attempt to partially establish that the schema is non-contradictory. I don't think it is practical and in any case just validating "default" and "enum" is not enough to achieve that goal.

> In my use case I working with very complex schema and this list show things that can't be validated using JSON Schema.

Generally I think that if something really can't be validated using JSON-schema then it shouldn't be. Trying to extend the standard, introduce custom keywords, abuse "format" keyword to use it for asynchronous validation, use hooks etc. is just an attempt to make yourself believe that you continue using a cross-platform tool when in reality you are no longer.

> But at the same time, you shouldn't limit experience users.

I share the belief that you should limit the experience if but not limiting it you are making it worse for majority of users / use cases...

> If you need to do many additional checks in different parts of JSON document, you end up traversing whole document so you loose all benefits of JSON Schema.

Main benefit of JSON-schema is not tree traversal. Tree traversal is trivial. Its main benefits are its declarative nature and effortless portability. By extending it you are losing these benefits.

Each tool has the scope where it can be efficiently applied and trying to use it outside of it rarely leads to good results - it usually reduces the value of the tool.

The solution is really simple - do the partial validation using JSON schema and do the rest of the validation with the code. This way the schema will stay cross-platform and the code will need to be ported, but the boundary will be clear. In case it's all hidden into a tangled mess of hooks and callbacks, nothing will be cross-platform.

But each to its own poison I guess. Don't take it personal please, just some flame war it seems :)

**Comment by IvanGoncharov** [comment]
>But each to its own poison I guess. Don't take it personal please, just some flame war it seems :)

I agree :)
