### ISSUE TITLE
Add column/line information to validation errors

### ISSUE THREAD

**Issue by whitlockjc** [zaggino/z-schema#120]
Over the weekend I played with [Esprima](http://esprima.org/) to generate an AST from JSON and then looked at what it would take to find column/line information based on an error path.  It was surprisingly easy and I think we could do a first pass at adding column/line information to z-schema error payloads but there are some concerns that I'll bring up later.  What I did was I took the `path` property of an error and used it to traverse the AST for the input value. 

To give you an idea of what I'm talking about, imagine you have this file as an input: https://github.com/apigee-127/swagger-tools/blob/master/examples/2.0/api/swagger.json  Now let's pretend that I had validation errors whose paths are represented below by `paths`:

```js
var paths = [
  [],
  ['paths'],
  ['paths', '/weather'],
  ['paths', '/weather', 'get'],
  ['paths', '/weather', 'get', 'parameters'],
  ['paths', '/weather', 'get', 'parameters', '0'],
  ['paths', '/weather', 'get', 'parameters', '0', 'in']
];
```

Playing around I was able to end up with matching locations that look like this:

```js
var locations = [
  '(L1#1)',
  '(L13#11)',
  '(L14#16)',
  '(L15#13)',
  '(L22#22)',
  '(L23#10)',
  '(L25#18)'
];
```

*(The example above is just showing you where in the validated value the error occurs.  I could also see this level of reporting being done with respect to where in the schema document the rule is where the validation failed.)*

Doing something like this would be pretty simple but to do it accurately depends on z-schema being aware of the raw input for the value being validated and/or schema file(s).  The reason for this can be displayed below where I show you two different ways of creating the string required to drive Esprima:

1. Driving Esprima with the raw input
2. Driving Esprima with `JSON.stringify` where I have to make assumptions about indentation *(This is the mode z-schema would have to rely upon.)*

**Driving Esprima with the raw input**
```js
'use strict';

var esprima = require('esprima');
var esprimaOptions = {
  loc: true
};
var fs = require('fs');
var swaggerDoc = fs.readFileSync('./api/swagger.json', 'utf-8');
var swaggerJson = 'var json = ' + swaggerDoc + ';'; // Required to make a valid JavaScript expression
var ast = esprima.parse(swaggerJson, esprimaOptions);

// Column numbers for line one need to be decremented by 10 to adjust for the preamble required to create a JavaScript expression 
```

**Driving Esprima with `JSON.stringify`**

```js
'use strict';

var esprima = require('esprima');
var esprimaOptions = {
  loc: true
};
var swaggerDoc = require('./api/swagger.json');
// Notice that `JSON.stringify` assumes your input was properly formatted, had no empty lines and used two-space indentation
var swaggerJson = 'var json = ' + JSON.stringify(swaggerDoc, null, 2) + ';'; // Required to make a valid JavaScript expression
var ast = esprima.parse(swaggerJson, esprimaOptions);

// Column numbers for line one need to be decremented by 10 to adjust for the preamble required to create a JavaScript expression
```

The second option will work but the generated column/line numbers could easily be off due to these situations:

* Empty lines
* Mixed indentation
* Assuming the wrong indentation
* ...probably others...

So in the end, I do like the idea of z-schema being able to find the column/line information for validation errors but I also think it would be very easy for this information to be wrong.  That being said, I'd like to propose that we discuss this openly.

**Comment by zaggino** [comment]
Definitely good looking feature - saying that probably out of scope of my time right now. If you'd be able to implement it together with some tests I'd definitely pull it in. You could probably try to detect the indentation from the json somehow to make it a bit more accurate but as you said, it'd be quite hard to deal with empty lines, mixed indent and so...

**Comment by whitlockjc** [comment]
I wouldn't mind doing the work but I don't see any good way to handle the empty lines, mixed indentation or identifying the indentation.  For the last one, we could make it configurable and make the default `2` like I did above.  Any attempt to provide an API to make things more accurate would likely be better in a different library.

**Comment by zaggino** [comment]
My only idea is, because z-schema works with a tree in memory obviously and not a file ... you can run the validation, collect the errors and then using the error paths walk the actual file and get the numbers from it?

**Comment by whitlockjc** [comment]
That would work but it would be one more step and one more API for the user to use.  But I guess if they want column/line information, it's just what they'd need to do.  Where this gets even more laborious is if we wanted to provide this information for the data tree and the schema tree(s) because then it would be multiple calls.

The more I think about it, some sort of `ZSchema#attachLOCToErrors` is more of an AST-specific API and not z-schema specific so would it even belong here?  Just thinking aloud here.

**Comment by braco** [comment]
+1, would like to use one of these json schema validators as a linter. Line numbers required for this task.

**Comment by zaggino** [comment]
It's possible to write a library which would collect errors from `z-schema` and then walk the AST tree to get the line numbers, but that doesn't really belong to this project.
