### ISSUE TITLE
Do not depend on request package

### ISSUE THREAD

**Issue by ismasan** [zaggino/z-schema#124]
Hi.

I'm using this package (thanks!) as included by Swagger Node.

When trying to use `npm shrinkwrap` on my project I see the following error:

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: request@^2.54.0, required by z-schema@3.12.0
```

However, searching in this library's source code I see that `request` only seems to be used in tests. 

My question is: Is it necessary to define `request` as a dependency, as opposed to a dev-dependency for tests only?

Regards.

**Comment by zaggino** [comment]
`request` is used only by command line interface, but I didn't make it a separate package. Would it help putting it into `optionalDependencies`?
