### ISSUE TITLE
Strange behavior with strict mode schema validation

### ISSUE THREAD

**Issue by dvelitchkov** [zaggino/z-schema#127]
I want to validate a schema if it's valid using the ```validateSchema``` call. In strict mode, the validator always fails for even the simplest of schemas (see below). However, if I re-initialize a new validator using non-strict mode, and then initialize a strict-mode validator a second time, schema validation succeeds. 

Reproduction:

```javascript
    var Validator = require('z-schema');
    var schema = {

    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "options": {
            "enum": ["a", "b", "c"]
        }
    },
    "additionalProperties": false
    };
    var v;
    v = new Validator({strictMode: true});
    console.log("strict mode valid: " + v.validateSchema(schema));   // prints false

    v = new Validator();
    console.log("normal mode valid: " + v.validateSchema(schema));   // prints true

    v = new Validator({strictMode: true});
    console.log("strict mode valid: " + v.validateSchema(schema));   // prints true?

```
I'm guessing it's some caching issue - didn't spend too much debugging it.

**Comment by zaggino** [comment]
Hi @dvelitchkov , this should be now fixed in `3.12.4`
