### ISSUE TITLE
Top-level errors obscure deeper errors...

### ISSUE THREAD

**Issue by the-t-in-rtf** [zaggino/z-schema#131]
If I omit a top-level field, it seems to prevent checking for deeper requirements.  Check out this example:

```
var ZSchema = require("z-schema");
var validator = new ZSchema();

var json = { "nested": { } };

var schema = {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Nested requirements don't work",
    "type":  "object",
    "properties": {
        "required": {
            "type": "string"
        },
        "nested": {
            "type": "object",
            "properties": {
                "required": {
                    "type": "string"
                }
            },
            "required": ["required"]
        }
    },
    "required" : ["required"]
};

validator.validate(json, schema);

console.log(JSON.stringify(validator.getLastErrors(), null, 2));
```

You would expect to see two errors, one for the top-level `required` field, and one for the nested field.  Z-schema only reports the error for the top-level field.  If you change the JSON to something like `var json = { "required": "valid", "nested": { } };`, the error is revealed.

Tools like [the JSON Schema Validator](http://json-schema-validator.herokuapp.com/) correctly report both errors in a single pass.

The real-world impact of this is that a user might have to correct one error before they hear about the other, which is less than ideal.

**Comment by zaggino** [comment]
Use https://github.com/zaggino/z-schema#breakonfirsterror for this.
Test attached: https://github.com/zaggino/z-schema/blob/master/test/ZSchemaTestSuite/Issue131.js

**Comment by the-t-in-rtf** [comment]
Thanks much for the quick response, @zaggino.  That works perfectly.
