### ISSUE TITLE
validate against subschema?

### ISSUE THREAD

**Issue by reesew** [zaggino/z-schema#132]
I'm attempting to use z-schema to validate data against schemas created using prmd. I'm wondering if z-schema has a way to validate an object against a subschema (e.g. in a definition) within the main schema document. For example, `validate({key: 1}, schema.definitions.widget)`. I can get this to work normally, but not in cases where the widget definition references something else in the schema (unresolvable reference).

**Comment by zaggino** [comment]
Ah, can you post a code sample? it's much easier to figure out what're you trying to do.

But if it's just matter of unresolvable reference, you can use after creating `validator` instance `validator.validateSchema(schemas);` where `schemas` is an array of all your schemas and then all references from your schemas should be saved inside the validator instance, so you should no longer get unresolvable reference

**Comment by reesew** [comment]
That sounds like exactly what I need. I'll try it out

**Comment by reesew** [comment]
It either didn't work as I expected, or I don't understand what was supposed to happen. I created a simple example to demonstrate what I'm seeing
https://gist.github.com/reesew/ccc1622ab3ff8c8d58fd

**Comment by zaggino** [comment]
Ah, now I see what you're trying to do.  It won't work like that easily. Why don't you split your schemas into multiple files and reference between them through id's? It's harder to maintain one large schema file than multiple smaller schema files ... see for example this test: https://github.com/zaggino/z-schema/blob/master/test/ZSchemaTestSuite/MultipleSchemas.js

**Comment by reesew** [comment]
That's what I was afraid of, but using prmd to manage and combine all the schemas from individual yaml files has been really nice. What would it take to get it to work with the use case from that gist? Would it fit in z-schema's scope? Maybe I could start working on a fork?

**Comment by zaggino** [comment]
I could probably implement something like:
```
var valid = validator.validate(json, schema, "definitions.car.definitions.cars")
```
which should fit your use case

**Comment by reesew** [comment]
That sounds handy

**Comment by losogudok** [comment]
```
var valid = validator.validate(json, schema, "definitions.car.definitions.cars")
```
+1 Very useful when you need to validate one field in a form.

**Comment by zaggino** [comment]
```
var valid = validator.validate(cars, schema, { schemaPath: "definitions.car.definitions.cars" });
```
implemented in `z-schema@3.14.0`

**Comment by shinymayhem** [comment]
That appears to have worked. Thank you!

**Comment by reesew** [comment]
Thank you
