### ISSUE TITLE
Validate method

### ISSUE THREAD

**Issue by simon-p-r** [zaggino/z-schema#134]
Hi

I encountered a problem where if I pass an empty json object to above method it passes validation against a valid schema which is not correct.  I can make a PR if you want.

Best regards
Simon

**Comment by zaggino** [comment]
Hi Simon, sure, exact code scenario or PR is appreciated.

**Comment by simon-p-r** [comment]
Here is a snippet of code that is failing

     validator.validate({}, schema, function (errors, valid) {

           console.log(err, valid)

     });

This logs errors null and valid true.  Schema looks like this

    { 
        id: 'dummy',
        properties: { 
            dbRef: { 
                type: 'object',
                format: 'dbRef',
                properties: [Object],
                additionalProperties: false 
            },
            luRef: { 
                type: 'object',
                format: 'lookup',
                properties: [Object],
                additionalProperties: false 
            },
            duration: { 
                type: 'string', 
                format: 'duration', 
                maxLength: 50 
             },
            additionalProperties: false,
            type: 'object',
            title: 'collection schema for dummy' 
       }
    }

**Comment by IvanGoncharov** [comment]
@simon-p-r You forget to add `"type": "object"` in top object.
According to [JSON Schema](http://json-schema.org/latest/json-schema-validation.html#anchor8):
>  When the primitive type of the instance cannot be validated by a given keyword, validation for this keyword and instance SHOULD succeed.

**Comment by simon-p-r** [comment]
It was a typo when I copied schema, the type object is at the correct level of object now.

**Comment by IvanGoncharov** [comment]
> passes validation against a **valid** schema

Did you mean invalid schema?
Because your schema is **invalid**, it has `properties: [Object]` inside.
It strange why `z-schema` didn't throw an error.

**Comment by simon-p-r** [comment]
I have updated schema, this is what was output of schema when I logged to console.  I tried to validate an empty json object against a valid schema and it passed the validation which is not desired behaviour.

**Comment by IvanGoncharov** [comment]
You forget to add `required` property, see [this](http://json-schema.org/latest/json-schema-validation.html#anchor61).
So if you add in top object: `"required": ["dbRef"]`, validation will fail.

**Comment by simon-p-r** [comment]
Ok thanks @IvanGoncharov that works as expected now.

**Comment by IvanGoncharov** [comment]
It always better to check you schema in some of the 3rd-party online validators, like this one:
http://jsonschemalint.com/draft4/
And if multiply validators are consistent in their behaviour, it probably better to post it here:
https://groups.google.com/forum/#!forum/json-schema

**Comment by simon-p-r** [comment]
:+1:  for the links

**Comment by IvanGoncharov** [comment]
@zaggino If something similar written in  README.md it will save a lot of time both for users and for maintainer.

**Comment by zaggino** [comment]
@IvanGoncharov z-schema will throw an error if schema is invalid, but this schema was valid, it just didn't have the `required` property

**Comment by simon-p-r** [comment]
Yes sorry for the noise, just wasn't the behaviour I expected.  I have been meaning to do a PR on docs so will try to include this when I get round to it!

**Comment by IvanGoncharov** [comment]
@simon-p-r No problem. 

> I have been meaning to do a PR on docs so will try to include this when I get round to it!

:+1:
