### ISSUE TITLE
undefined subschema

### ISSUE THREAD

**Issue by shinymayhem** [zaggino/z-schema#135]
This is related to #132 and/or `~3.14.0`
When an invalid schemaPath is specified, such as 
`var valid = validator.validate(cars, schema, { schemaPath: "definitions.car.definitions.chars" });`
(which doesn't exist) instead of 
`var valid = validator.validate(cars, schema, { schemaPath: "definitions.car.definitions.cars" });`

the error is a little cryptic. 
```
schema valid:  true
/schemas/sandbox/node_modules/z-schema/src/JsonValidation.js:440
        report.addError("SCHEMA_NOT_AN_OBJECT", [to], null, schema.description
                                                                  ^
TypeError: Cannot read property 'description' of undefined
```
So it isn't really a bug, per se, but I wasn't originally sure what the error meant or how to debug further.
I wanted to submit a quick pull request, but wasn't clear on the best place to fix this. Maybe a check for undefined around https://github.com/zaggino/z-schema/blob/39b7dc615a74187d7b97cb66e39fa997035717ff/src/ZSchema.js#L194 ?

**Comment by zaggino** [comment]
Released your PR in `3.14.2`
