### ISSUE TITLE
Report.addError method

### ISSUE THREAD

**Issue by simon-p-r** [zaggino/z-schema#139]
Hi

Can a param of name or id be added to above method?  When validating an array of schemas it would be good to get the context of which schema failed along with the code, message and path.

Thanks
Simon

**Comment by zaggino** [comment]
Can you submit a test or a code example?

**Comment by simon-p-r** [comment]
```js
var dummy = {

        id: 'dummy',
        type: 'object',
        description: 'This is a dummy schema',
        properties: {
            recType: {
                type: 'string'
            },
            startDate: {
                type: ['object', 'string'],
                format: 'date'
            },
            endDate: {
                type: ['object', 'string'],
                format: 'date'
            },
            noteList: {
                type: 'array',
                items: {
                    $ref: 'note'
                }
            },
            isBlocked: {
                type: 'boolean'
            },
            roleA: {
                $ref: 'dbRef'
            },
            roleB: {
                $ref: 'dbRef'
            },
            recProps: {
                type: 'object'
            }

        },
        additionalProperties: false,
        required: ['recType','roleA','roleB']

};

````

This is my test schema that is failing due to issues with $ref plus maxLength and object properties as using strictMode true..

**Comment by zaggino** [comment]
and what do you expect to see in the error? `dummy`? what if some other element has an `id` attribute, should we use the closest one, or the root one? this isn't very specific

**Comment by simon-p-r** [comment]
Yes dummy would be a good way of identifying where schema is failing.  If root schema is used then name / id could be them split by / like paths are shown currently.  I only use lots of smaller schemas as I find one big tree of schemas inflexible and difficult to maintain.  I will do a PR if you want with test to show it working.

**Comment by zaggino** [comment]
PR would be great, I don't mind this feature but a good set of tests needs to come with it.

**Comment by simon-p-r** [comment]
I have made a start here https://github.com/simon-p-r/z-schema/commit/5d07f6adc57072f1ef6beeda9dd27f7d109e0a2f but can't get test to pass.  All other tests pass.

**Comment by zaggino** [comment]
i'm afraid it's not as simple as you tried but the test is good, can you submit a PR with the test? i'll take a look at this when i'll have some time next week

**Comment by zaggino** [comment]
Fixed by https://github.com/zaggino/z-schema/commit/d3d0566c7f15a563b92032f62e6919a5c6defd96
