### ISSUE TITLE
assumeAdditional complains about $ref

### ISSUE THREAD

**Issue by ralfhandl** [zaggino/z-schema#142]
I checked some schemas against draft04 and switched on assumeAdditional to check for undeclared properties. This resulted in lots of errors complaining about 'Additional properties not allowed: $ref'.

When I experimentally checked draft04 against itself I also got such an error:

{ code: 'OBJECT_ADDITIONAL_PROPERTIES',
  params: [ [ '$ref' ] ],
  message: 'Additional properties not allowed: $ref',
  path: '#/properties/not',
  description: 'Core schema meta-schema' }

This seems overeager: I would assume that JSON References are exempt from assumeAdditional:true, otherwise this feature is somewhat reduced in usefulness.

**Comment by zaggino** [comment]
Can you please submit a testcase?

**Comment by ralfhandl** [comment]
Hi Martin,

This reproduces my problem:

```javascript
// Validate JSON Schema Draft 04 against itself

var fs = require('fs');
var util = require('util');

var draft04 = JSON.parse(fs.readFileSync("json-schema-draft-04.json"));

var ZSchema = require("z-schema");

var validator = new ZSchema({
    noExtraKeywords : true,
    assumeAdditional : true
  });

var valid = validator.validate(draft04, draft04);
if (valid != true) {
  console.log("-- fails:");
  console.log(validator.getLastErrors()[0]);
} else {
  console.log("validation: SUCCESS");
}
```
The file json-schema-draft-04.json contains the draft00 schema at http://json-schema.org/draft-04/schema# 

Thanks in advance!
--Ralf

**Comment by ralfhandl** [comment]
In the meantime I'm proceeding by manually placing "additionalProperties":false into my schemas and explicitly allowing JSON references with anyOf constructs that include objects only having a $ref property. Now I get another surprising error:

   message: 'Additional properties not allowed: __$refResolved',

I assume these properties are injected by z-schema when resolving references.

**Comment by zaggino** [comment]
Hi @ralfhandl , `noExtraKeywords` rule applies only when schema you're using doesn't have parent schema. If it has parent schema (`$schema` keyword), it's up to the parent schema to decide whether extra keywords are or aren't allowed.

**Comment by zaggino** [comment]
So looking into this, `draft-04-schema` doesn't specify `$ref` explicitly in `properties` or `patternProperties` and it also doesn't specify `additionalProperties` in the root. Using `assumeAdditional: true` means validator will set `undefined` additionalProperties to `false` and hence the validation will fail. This behaviour is correct.

**Comment by zaggino** [comment]
@ralfhandl you can use: `assumeAdditional: ["$ref"]` to allow `$ref` specifically in version `3.16.0`
see https://github.com/zaggino/z-schema/commit/dcf3e4650733d28d5572553e18a6afd77e77ec9f for details

**Comment by ralfhandl** [comment]
Thanks, just what I needed!
