### ISSUE TITLE
Question: structure of options parameter in validate() method.

### ISSUE THREAD

**Issue by red-0ne** [zaggino/z-schema#144]
In order to make a typescript definition entry for z-schema. We want to be as strict as possible regarding the manipulated data structures.

So when we tried to define the `options` object passed to `validator.validate()`, we found that the only option used is `options.schemaPath`. Are we missing something, or declaring it as `type ValidatorOptions = { schemaPath: string }` is sufficient?

**Comment by zaggino** [comment]
Hi @red-0ne , that's right, it's the only option for `validate` method right now, used for validating sub-schemas.

**Comment by red-0ne** [comment]
Hi @zaggino, here is what I came with. Could you please check if it's ok or not?
https://gist.github.com/red-0ne/91031452946dfe32250d

**Comment by zaggino** [comment]
Hi @red-0ne , sorry for the late answer, seems right, but I've never used TypeScript so this is not very familiar to me.
