### ISSUE TITLE
Only the first failure in an `allOf` block is returned as an error...

### ISSUE THREAD

**Issue by the-t-in-rtf** [zaggino/z-schema#146]
Even if`breakOnFirstError` is disabled, an `allOf` block with multiple failing rules only returns information about the first failing rule.  For example, if I want to validate a password, I might use code like the following:

```
var ZSchema = require("z-schema");
var validator = new ZSchema({
    breakOnFirstError: false
});

var schema = {
  properties: {
    password: {
      allOf: [{ type: "string", minLength: 8},{ type: "string", pattern: "[A-Z]+"}]
    }
  }
}

var content = {
  password: "short"
};

var hasErrors = validator.validate(content, schema);
if (!hasErrors) {
  console.log("Validation Errors:", JSON.stringify(validator.getLastErrors(), null, 2));
}
```

This script returns the following output:

```
Validation Errors: [
  {
    "code": "PATTERN",
    "params": [
      "[A-Z]+",
      "short"
    ],
    "message": "String does not match pattern [A-Z]+: short",
    "path": "#/password"
  }
]
```

There is no mention that two rules failed.  This means in practice that users may be presented with one error that they have to fix, and then will be presented with the second.  With the `breakOnFirstError` option set to `false`, I would expect output like:

```
 [
  {
    "code": "PATTERN",
    "params": [
      "[A-Z]+",
      "short"
    ],
    "message": "String does not match pattern [A-Z]+: short",
    "path": "#/password"
  },
  {
    "code": "MIN_LENGTH",
    "params": [
      5,
      8
    ],
    "message": "String is too short (5 chars), minimum 8",
    "path": "#/password"
  }
]
```

This is what tools like [https://json-schema-validator.herokuapp.com/] do for multiple failures, and is more useful in providing complete feedback in a single pass.

**Comment by zaggino** [comment]
Published fix as `3.15.4`
