### ISSUE TITLE
Problems using browser version of z-schema when noTypeless set to true.

### ISSUE THREAD

**Issue by DNR500** [zaggino/z-schema#150]
Hi,

I've been trying to get a version of the client-side z-schema working with jasmine in a headless browser for testing.

Everything seems to work fine until I set the option noTypeless to true.

I've put together a small sample of the code here 

https://github.com/DNR500/z-schema-example

The gruntfile passes the json schemas to the unit tests via the templateOptions in the jasmine task

https://github.com/DNR500/z-schema-example/blob/master/Gruntfile.js (see line 23)

The spec runner file picks these up and adds them as javascript variables (a version of the generated output of this file is placed in the "generated" folder when "grunt jasmine" is run).

https://github.com/DNR500/z-schema-example/blob/master/vendor/test/lib/SpecRunner.html (see line 21)

In the test both the draft and custom schema get used - works fine until noTypeless is added to the test (remove that line and the test will work fine).

https://github.com/DNR500/z-schema-example/blob/master/tests/specs/schematest.js (see line 7)

Am I missing something obvious here or is this a bug? The error I seem to get is REMOTE_NOT_VALID but I thought setting the draft 4 spec using setRemoteReference would sort that.

Any help you could give would be appreciated.

Thanks 

Nathan

**Comment by zaggino** [comment]
Hi Nathan, when I clone your repo and run `grunt jasmine` it freezes for me:
```
Zaggi@CO9QUQM MINGW64 /c/dev/z-schema-example (master)
$ grunt jasmine
Running "jasmine:spec" (jasmine) task
Testing jasmine specs via PhantomJS
```

**Comment by zaggino** [comment]
What's the complete error json? `REMOTE_NOT_VALID` error should contain some child errors to say, why the remote is not valid.

**Comment by DNR500** [comment]
Thats odd. I've just clone the project on a different machine to what I originally developed the project on. managed to clone it and after an npm install, running grunt jasmine worked fine.

node version - v4.0.0
npm version - 2.14.2

Error looks like the below

```javascript
{
    "code": "REMOTE_NOT_VALID",
    "params": [
        "http://json-schema.org/draft-04/schema#"
    ],
    "message": "Remote reference didn't compile successfully: http://json-schema.org/draft-04/schema#",
    "path": "#/uri(http://json-schema.org/draft-04/schema)",
    "schemaId": "http://jsonschema.net",
    "inner": [
        {
            "code": "KEYWORD_UNDEFINED_STRICT",
            "params": [
                "type"
            ],
            "message": "Keyword 'type' must be defined in strict mode",
            "path": "#/uri(http://json-schema.org/draft-04/schema)/properties/default",
            "schemaId": null
        },
        {
            "code": "KEYWORD_UNDEFINED_STRICT",
            "params": [
                "type"
            ],
            "message": "Keyword 'type' must be defined in strict mode",
            "path": "#/uri(http://json-schema.org/draft-04/schema)/definitions/positiveIntegerDefault0/allOf/1",
            "schemaId": null
        },
        {
            "code": "KEYWORD_UNDEFINED_STRICT",
            "params": [
                "type"
            ],
            "message": "Keyword 'type' must be defined in strict mode",
            "path": "#/uri(http://json-schema.org/draft-04/schema)/definitions/positiveIntegerDefault0",
            "schemaId": null
        }
    ]
}
```

**Comment by zaggino** [comment]
```
#/uri(http://json-schema.org/draft-04/schema)/properties/default
```
this is defined as `"default": {},` so `noTypeless` is correct to throw an error

**Comment by zaggino** [comment]
```
#/uri(http://json-schema.org/draft-04/schema)/definitions/positiveIntegerDefault0/allOf/1
```
is reffering to: `{ "default": 0 }` which again doesn't have type defined

**Comment by zaggino** [comment]
```
#/uri(http://json-schema.org/draft-04/schema)/definitions/positiveIntegerDefault0
```
is reffering to
```
"positiveIntegerDefault0": {
                        "allOf": [
                            { "$ref": "#/definitions/positiveInteger" },
                            { "default": 0 }
                        ]
                    }
```
and there's also type missing for the `positiveIntegerDefault0`
