### ISSUE TITLE
minProperties for object type doesn't work

### ISSUE THREAD

**Issue by boazshor** [zaggino/z-schema#151]
I created a json schema as follows:
{
    "type": "object",
    "properties": {
            "props":{ "type": "object","minProperties": 1}
     }
}

and passed the validate function the schema above and the following object:
{
   "props":{}
}
the validation returned that the object is valid and no errors were found.

Thanks.

**Comment by zaggino** [comment]
you're doing something wrong, I put together a testcase with your example and it passes fine: https://github.com/zaggino/z-schema/commit/108fd65e83512d4867ba13b9c97455ff860e2b92
