### ISSUE TITLE
Support Buffer objects

### ISSUE THREAD

**Issue by whitlockjc** [zaggino/z-schema#152]
What do you think about supporting `Buffer` objects to represent strings?  Take for example Express.  It converts `String` instances to `Buffer` instances and if I try to validate it as a string with z-schema, I get a type mismatch error of course: `Expected type string but found type object`.  I thought about submitting a PR but I didn't want to make the assumption that you'd even want to support it.

What are your thoughts on treating `Buffer` objects as `String` objects?

**Comment by whitlockjc** [comment]
By the way, the first thing I can think of that might throw a wrinkle in this is turning a `Buffer` into a `String` to do the actual validation might require you knowing the encoding.  This could have an impact in the API.

**Comment by zaggino** [comment]
What'd be the benefit of directly supporting Buffer instead of just letting it to the developer to do the buffer -> string conversion before calling z-schema?

**Comment by whitlockjc** [comment]
Good question.  I'm not 100% sure who *should* own it.  I could see requiring the caller to do it but that quickly gets nasty in the event of arrays/objects where you have to do a precursory walk of the tree to translate things only to have z-schema walk the tree again.

I'd understand why you wouldn't want to support it but with `Buffer` being used in a number of Node.js libraries like Express, I just figured I'd ask before doing this myself for my project(s).

**Comment by zaggino** [comment]
In this case I think it'd give the project code complexity and branching it doesn't really need. Also I'm not sure about web browser support.

**Comment by whitlockjc** [comment]
Works for me.  I'll work around it and we can revisit if need be.  Thanks for your input.
