### ISSUE TITLE
custom "format" attributes

### ISSUE THREAD

**Issue by danfowler** [zaggino/z-schema#153]
From http://json-schema.org/latest/json-schema-validation.html#anchor104

 ```
Implementations MAY support the "format" keyword. Should they choose to do so:

    they SHOULD implement validation for attributes defined below;

    they SHOULD offer an option to disable validation for this keyword.
```

My [schema](https://github.com/dataprotocols/schemas/blob/master/data-package.json) uses custom values for "format" and so fails validation using z-schema.  Is there a way to disable validation for this keyword?

**Comment by zaggino** [comment]
There's already an option `ignoreUnknownFormats`, doesn't it do what you need? https://github.com/zaggino/z-schema#ignoreunknownformats

**Comment by danfowler** [comment]
Ah, I think the reason I missed it is because it isn't available through the CLI.  Thanks :).

**Comment by zaggino** [comment]
fixed
```
$ z-schema --ignoreUnknownFormats schema.json
schema validation passed
```
works in 3.16.1

**Comment by danfowler** [comment]
:+1:
