### ISSUE TITLE
Compiling multiple schemas with shared references without ids

### ISSUE THREAD

**Issue by whitlockjc** [zaggino/z-schema#154]
Let's say I have two schemas:

```js
{
  definitions: {
    Person: {
      type: 'object',
      properties: {
        age: {
          type: 'integer'
        },
        name: {
          type: 'string'
    }
      },
      required: ['name']
    }
  }
}
```

```js
{
  $ref: '#/definitions/Person'
}
```

The idea is that I want to validate a value against the second schema but it's got references to the first schema.  The first schema does not have an `id` so so z-schema fails to compile the two schemas.  Is there any way to compile a reference that is dependent/linked/... against another without using `id` properties?

Programmatically I can rectify this at runtime by injecting an `id` property into the first document and then updating all references in the second document to be prepended with the `id` injected into the first document.  This is likely the approach I'll have to take but before I go down that path, I was wondering if there was another way.  It would be cool to be able to have a *root* schema and compile other schema(s) against that root such that references without an id default to resolving against that *root* document.

I started working on a PR that did this but it didn't work.

**Comment by zaggino** [comment]
I don't think what you're trying to do is valid, `#/definitions/Person` should point to the `Person` definition in the same schema, not in a different schema. Perhaps you want to merge those two before validating?

**Comment by whitlockjc** [comment]
That's what I figured.  The two options I see:

1. Merge schemas
2. Add an `id` to the first schema and update all `$ref` to be prefixed by the same id so that it looks like `{id}{$ref}`

That second option works with z-schema as expected, I tried it.  I guess we can close this.  I just wanted your opinion before I started a PR.
