### ISSUE TITLE
format validators

### ISSUE THREAD

**Issue by cgarnier** [zaggino/z-schema#168]
Hello,
I dont understand why when the value type is not the expected one, you assume value is valid.
Is there a reason for that ?

https://github.com/zaggino/z-schema/blob/master/src/FormatValidators.js#L47
For exemple, for the email validator. If i put and integer or something else then a string, it assuming value is valid.

**Comment by IvanGoncharov** [comment]
@cgarnier It's implemented according to spec:
http://json-schema.org/latest/json-schema-validation.html#anchor104
> A format attribute can generally only validate a given set of instance types. If the **type of the instance to validate is not in this set**, validation for this format attribute and instance **SHOULD succeed**.

Just add `type` keyword in your schema it will also help with other things.
Like `minimum` is will validate strings, and many similar things.
I recommend you to enable this flag:
https://github.com/zaggino/z-schema#notypeless

**Comment by cgarnier** [comment]
Ok, thanks!
