### ISSUE TITLE
Gauging Interest in PR for removing Request as dependency

### ISSUE THREAD

**Issue by TheToolbox** [zaggino/z-schema#173]
The request library now offers more features than are necessary in z-schema.
There were two total references to it by my measure, one of which is a test ([1](https://github.com/zaggino/z-schema/blob/master/bin/z-schema), [2](https://github.com/zaggino/z-schema/blob/master/test/spec/AutomaticSchemaLoadingSpec.js)).

Removing the dependency and writing nodejs native code was a <20 LOC difference, and should provide equivalent error coverage. I ran grunt and it passed all tests (although I did get 3 validateIndentation errors from jscs in test/spec/schemaPathSpec.js, which was unmodified).

 - Is this something desired?
 - If so, what steps should I follow to build for a PR?

Issue noted here: https://github.com/apigee-127/sway/issues/97

**Comment by zaggino** [comment]
Hi, I'll merge your PR if no tests fail, simple :-)
