### ISSUE TITLE
Validation for defined properties fails with "additional properties not allowed"

### ISSUE THREAD

**Issue by bgaluszka** [zaggino/z-schema#175]
This

```js
var ZSchema = require('z-schema');

var validator = new ZSchema({
    assumeAdditional: true
});

var schema = { 
    "description":"User",
    "type":"object",
    "allOf":[
        {   
            "type":"object",
            "required":["id"],
            "properties":{
                "id":{
                    "description":"Id",
                    "type":"integer"
                }   
            }   
        },  
        {   
            "type":"object",
            "required":["name"],
            "properties":{
                "name":{
                    "description":"Name",
                    "type":"string"
                }   
            }   
        }   
    ]   
};

var data = { 
    "id": 1,
    "name": "Name"
};

var valid = validator.validate(data, schema);

if (valid) {
    console.log("Valid");
} else {
    console.log(validator.getLastErrors());
}
```

fails for me with

```json
[
    {
        code: 'OBJECT_ADDITIONAL_PROPERTIES',
        params: [ [Object] ],
        message: 'Additional properties not allowed: id',
        path: '#/',
        schemaId: undefined
    }
]
```

**Comment by bgaluszka** [comment]
Just to clarify I wanted to test if `data` doesn't have additional properties not defined in schema.

**Comment by zaggino** [comment]
@bgaluszka your object doesn't pass second schema in `allOf` because the second schema doesn't specify `id`

**Comment by zaggino** [comment]
use
```
var schema = { 
    "description":"User",
    "type":"object",
    "required":["id", "name"],
    "properties":{
                "id": {
                     "type":"integer"
                },
                "name":{
                    "description":"Name",
                    "type":"string"
                }   
            }

**Comment by bgaluszka** [comment]
I know how to make it pass :) That's not an issue here. Schema definition is valid and validator should validate it properly but it isn't.

**Comment by zaggino** [comment]
`assumeAdditional` is a feature which dont allows unspecified properties. in this case one of your `allOf` schemas is missing `id` property ... it will pass the validation if you turn the feature off

**Comment by bgaluszka** [comment]
But shouldn't `allOf` combine properties of all schemas in it's array before validating it (or something like that)? Point of adding `assumeAdditional: false` in my case was exactly what you said, I don't want additional properties. So something like this fails:

```
var data = { 
    "id": 1,
    "name": "Name",
    "additional": true
};
```

**Comment by bgaluszka** [comment]
Ok, seems like I misunderstood how it works and that schemas are evaluated independently http://stackoverflow.com/a/23001194 - `schema1 and schema2 have no knowledge of one another; they are evaluated in their own context.`
