### ISSUE TITLE
getLastErrors() returning only last one if occurs on minLength

### ISSUE THREAD

**Issue by raphaelkoszalka** [zaggino/z-schema#182]
Hello everyone,

I'm using z-schema to validate my forms, but i've found when testing my application that if i have lets say 4 fields with minLength setted, the getLastErrors() method returns only the last one, not all errors.

Does anyone have a fix for this?

**Comment by zaggino** [comment]
Use `breakOnFirstError: false` option.
https://github.com/zaggino/z-schema#breakonfirsterror
