### ISSUE TITLE
remove async mode?

### ISSUE THREAD

**Issue by kevinburke** [zaggino/z-schema#190]
It seems like all of the validators run synchronously, and the only benefit to the provided async mode is to run in the next tick. Users may be confused by the presence of an asynchronous mode that the package is attempting to open a socket or a file or some other syscall that involves I/O.

A user could handle moving calls to the next tick themselves by calling `process.nextTick` and then using the synchronous API, e.g.

```javascript
process.nextTick(function() { 
    validator.validate(...)
});
```

That seems strictly better since you'd have more control that way.

**Comment by simon-p-r** [comment]
@kevinburke functions to validate custom formats are allowed to run async therefore this mode should not be removed.  Must other validators run sync which is one of the major advantages of this library.

**Comment by zaggino** [comment]
@simon-p-r is right here
