### ISSUE TITLE
Built-in draft 4 metaschema is unusable with strict options

### ISSUE THREAD

**Issue by pgonzal** [zaggino/z-schema#191]
Internally ZSchema does this on startup:

```javascript
function ZSchema(options) {
    this.cache = {};
    this.referenceCache = new ReferenceCache();

    this.setRemoteReference("http://json-schema.org/draft-04/schema", Draft4Schema);
    this.setRemoteReference("http://json-schema.org/draft-04/hyper-schema", Draft4HyperSchema);
```

This allows you to reference the metaschema when writing your own schema, like this:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema",

  "id": "my-example.schema.json",

  "type": "string",
  "minLength": 5,
  "maxLength": 14
}
```

However, if you try to turn on ZSchema's "strict" options, the "my-example.schema.json" fails to compile because the Draft4Schema itself violates most of the strict rules.

What's the right fix for this?

1. Change the Draft4Schema to be more rigorous, so it passes the strictest settings.
2. Allow `setRemoteReference()` to specify its own options for handling the remote reference.
3. Disable strict checking entirely for remote references.

**Comment by zaggino** [comment]
Hi @pgonzal , both 2 and 3 (as an configurable option) would be acceptable as pull requests.

**Comment by pgonzal** [comment]
Please take a look at my PR #197

**Comment by zaggino** [comment]
Solved in https://github.com/zaggino/z-schema/pull/197
