### ISSUE TITLE
Add different error codes for value not present in enum v/s case not matching

### ISSUE THREAD

**Issue by amarzavery** [zaggino/z-schema#202]
Today z-schema [emits ENUM_MISMATCH error](https://github.com/zaggino/z-schema/blob/8c6bb4aa1f51f87984cd4821057871a1c5e241ae/src/JsonValidation.js#L257) when it cannot find a value that exactly matches one of the values in the enum array. This is good.

However there are cases where we are interested in knowing that the mismatch
 happened due to case sensitivity or because the value was not found.

A suggestion about the new error code:
It would be nice if z-schema can emit the current error code "ENUM_MISMATCH" when a matching value is not found in the enum array and emit a new error code "ENUM_CASE_MISMATCH" when a value was found but the casing did not match. This would be less breaking and more helpful to lot of customers.

We are perfectly fine if you want to chose a different name. However, having different error codes would be super helpful. It would be better if one can configure this behavior  by providing an option while instantiating z-schema. In that way the current behavior can stay as-is (the default behavior) and people who choose to get different error codes can get that as well.

What do you guys think?

**Comment by zaggino** [comment]
hi, @amarzavery feel free to put up a PR, ideally without any breaking changes, new option sounds good
