### ISSUE TITLE
Allow override of Json validators

### ISSUE THREAD

**Issue by vladbarosan** [zaggino/z-schema#204]
These are defined here https://github.com/zaggino/z-schema/blob/master/src/JsonValidation.js  and are not exported. 

Since there are various scenarios for users can we allow those to be overridden ?

**Comment by zaggino** [comment]
Hi, they are implemented according to JSON schema spec. Not sure it'd be wise to override them? Can you provide your use-case? But if you want to create a PR with test and expose these, I don't mind it.

**Comment by vladbarosan** [comment]
@zaggino thanks for the quick reply. 

The scenario's would be when you would want to differentiate more in detail than the existing errors codes. ( one example whould have been the difference between enum case mismatch and just a wrong value.

In general there might be various reasons for people wanting to customize the validation ( maybe even to relax it from the official JSON ). 

The only valid concern I can see is if you plan to restructure how z-schema works and that would force you into a breaking change in case those are exposed. 

I'll make a PR if my latest point you don't think its a concern

**Comment by zaggino** [comment]
solved in https://github.com/zaggino/z-schema/pull/225 (if not, submit a PR please so I'll have a look)
