### ISSUE TITLE
Paths in errors are incorrect due to Issue #209 fix

### ISSUE THREAD

**Issue by gorlox19** [zaggino/z-schema#229]
With commit https://github.com/zaggino/z-schema/commit/b4444bf779f50f78fc1cccf2f1f5306904f51dc4, paths in error messages now contain all properties in the object and not just the one with the issue.  For example, I have a definition of:
```json
{
  "allOf": [
    {
      "properties": {
        "setup": {
          "description": "Account Research Setup",
          "properties": {
            "excessiveCredit": {
              "properties": {
                "negativeBatch": {
                  "type": "number",
                  "format": "double",
                  "minimum": 0,
                  "maximum": 999999999.99,
                  "title": "Negative Batch $"
                },
                "amountOfCreditsInBatch": {
                  "type": "number",
                  "format": "double",
                  "minimum": 0,
                  "maximum": 999999999.99,
                  "title": "Amount of Credits in a Batch $"
                },
                "numberOfCreditsInBatch": {
                  "type": "number",
                  "minimum": 1,
                  "maximum": 999,
                  "title": "Number of Credits in a Batch"
                }
              }
            }
          }
        }
      }
    }
  ]
}
```
and data of
```json
{
  "setup": {
    "excessiveCredit": {
      "amountOfCreditsInBatch": -15000.21,
      "negativeBatch": 25001,
      "numberOfCreditsInBatch": 155
    }
  }
}
```
I would expect a single error with the path of
```json
[
  "setup",
  "excessiveCredit",
  "numberOfCreditsInBatch"
]
```
But with the new changes, the path to the error is now
```json
[
  "setup",
  "excessiveCredit",
  "numberOfCreditsInBatch",
  "negativeBatch",
  "amountOfCreditsInBatch"
]
```
The line of code that commented out the `pop` forces all other properties into the path of a single error

**Comment by Kent55** [comment]
@gorlox19 I have experienced this also, we've had to temporarily pin back to `3.24.2`.

**Comment by TatyanaBol** [comment]
We have experienced this issue too! 
We are using swagger-tools that use z-schema as its dependency. 
In the swagger-tools' package.json it is written `"z-schema": "^3.15.4" `. 
Unfortunately, we can not tell swagger-tools which version of z-schema it should use.
Our tests started to fail 2 days ago.
We have a critical bug in our service because of this issue and can't promote our code to production. It's a show stopper!
Do you have an estimation when it will be fixed?

**Comment by Kent55** [comment]
@zaggino any updates on this? It is causing our tests to fail and blocking us also. Ideally, we don't want to be running a pinned version for too long.
