### ISSUE TITLE
why when schema type is string, there is no error when the value type is integer or number ?

### ISSUE THREAD

**Issue by vladbarosan** [zaggino/z-schema#235]
Hi @zaggino ,  can you please specify why we dont report an error in this case ? 
https://json-schema.org/understanding-json-schema/reference/string.html#string

**Comment by zaggino** [comment]
Not sure what you're pointing at here? Are you talking about z-schema potential bug or something in json-schema specification?

**Comment by vladbarosan** [comment]
@zaggino sorry actually the issue was coming from another dependency doing some type coercion
