### ISSUE TITLE
Remove core-js

### ISSUE THREAD

**Issue by Azzurite** [zaggino/z-schema#247]
I don't want weird advertisements in my command line whenever I do `npm install`. That's why I decided against using z-schema, even if it would've been a good fit.

Does this project really need core-js that much? Aren't there other, better polyfills, that don't advertise in the command line?

**Comment by pubkey** [comment]
You can disable the log with an ENV variable. See here https://github.com/zloirock/core-js/blob/5a66505301b64d13f7bcf96b1e9ab55e4ff35fe6/packages/core-js/postinstall.js#L10

**Comment by zaggino** [comment]
This is now fixed, `core-js` is no longer required anyway since the project doesn't support node version 4 anymore.
