### ISSUE TITLE
'email' format accepts email addresses with several types of whitespace.

### ISSUE THREAD

**Issue by shane-tomlinson** [zaggino/z-schema#252]
Email addresses are considered valid even if they have any of the following types of whitespace:

* no-break space (U+00A0)
* zero-width space (U+200B)
* left-to-right mark (U+200E)
* right-to-left mark (U+200F)

There may be more, I only tried these and a few more.

Here is a test suite that shows the problem:

```js
"use strict";

module.exports = {
    description: "email format validation with non-visible whitespace",
    schema: {
        type: "string",
        format: "email"
    },
    tests: [
      {
        description: "no break space space should not pass validation #1",
        data: "my_email\u00A0@gmail.com",
        valid: false
    },
    {
      description: "zero-width space should not pass validation #2",
      data: "my_email\u200B@gmail.com",
      valid: false
    },
    {
        description: "left to right mark should not pass validation #3",
        data: "my_email\u200E@gmail.com",
        valid: false
    },
    {
        description: "right to left mark should not pass validation #4",
        data: "my_email\u200F@gmail.com",
        valid: false
    }
    ]
};
```

**Comment by shane-tomlinson** [comment]
Looking at the [IETF spec about internationalized email addresses](https://tools.ietf.org/html/rfc6531#section-3.2), email addresses *are* allowed to contain utf-8 characters:

> An SMTP server that announces the SMTPUTF8 extension MUST be prepared
   to accept a UTF-8 string [RFC3629] in any position in which RFC 5321
   specifies that a <mailbox> can appear.  Although the characters in
   the <local-part> are permitted to contain non-ASCII characters, the
   actual parsing of the <local-part> and the delimiters used are
   unchanged from the base email specification [RFC5321].

So perhaps this issue is invalid, and the latest specs are being followed. Is there any value in having two modes for email validation, one that accepts utf-8 characters in the local part, and another that does not?

```
diff --git a/src/FormatValidators.js b/src/FormatValidators.js
index 3406052..8d0aa29 100644
--- a/src/FormatValidators.js
+++ b/src/FormatValidators.js
@@ -47,7 +47,7 @@ var FormatValidators = {
         if (typeof email !== "string") {
             return true;
         }
-        return validator.isEmail(email, { "require_tld": true });
+        return validator.isEmail(email, { "require_tld": true, "allow_utf8_local_part": false });
     },
     "hostname": function (hostname) {
         if (typeof hostname !== "string") {
```

**Comment by zaggino** [comment]
You can do in your project:
```
const validator = require('validator'); // already imported by z-schema so you don't need it as dependency in package.json
ZSchema.registerFormat(
    "email",
    function (email) {
        if (typeof email !== "string") {
            return true;
        }
        return validator.isEmail(email, { "require_tld": true, "allow_utf8_local_part": false });
    }
);
```
I wouldn't modify the default behaviour unless we need to match the official test suite (maybe open a PR there?): https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft4/format.json

**Comment by shane-tomlinson** [comment]
Thanks @zaggino - closing this issue!
