### ISSUE TITLE
Support v5 Proposals

### ISSUE THREAD

**Issue by zaggino** [zaggino/z-schema#51]
https://github.com/json-schema/json-schema/wiki/v5-Proposals

**Comment by handrews** [comment]
draft-06 is out!

[Guide for core and validation](https://github.com/json-schema-org/json-schema-spec/wiki/FAQ:-draft-wright-json-schema%5B-validation%5D-01)
[Guide for hyper-schema](https://github.com/json-schema-org/json-schema-spec/wiki/FAQ:-draft-wright-json-schema-hyperschema-01)

**Comment by handrews** [comment]
draft-07 is out! (or rather, was out in November)

[Guide for core and validation](http://json-schema.org/draft-07/json-schema-release-notes.html)
[Guide for hyper-schema](http://json-schema.org/draft-07/json-hyper-schema-release-notes.html)

Note that implementations that do not support at least draft-06 will soon be moved to an "obsolete" section of the json-schema.org web site.  Implementations supporting draft-06 or newer will remain prominently featured on the existing implementations page.

**Comment by zaggino** [comment]
I don't think i'm going to work on this anytime soon due to time issues, I keep using v4 in my projects for now.
