### ISSUE TITLE
Custom error messages

### ISSUE THREAD

**Issue by a00andos** [zaggino/z-schema#72]
Hi! 

Is it possible to create custom error messages in an easy way with z-schema?
Like if I am developing for another language and want proper error messages.

**Comment by Sebastian-G** [comment]
@zaggino you referred to master.

Links with right CommitID (updated):
> Definitely and it's designed to be quite easy. You can see here that every error contains properties code and params: https://github.com/zaggino/z-schema/blob/89f1675a5057c93aae7adb8006e3e7688dad143c/src/Report.js#L104-L109
> 
> Only thing you need to do when you'll get errors out from z-schema is go through the errors and create a new message using those code and params like this: https://github.com/zaggino/z-schema/blob/89f1675a5057c93aae7adb8006e3e7688dad143c/src/Report.js#L98-L102
> 
> List of all error codes can be found here: https://github.com/zaggino/z-schema/blob/master/src/Errors.js
