### ISSUE TITLE
ignoreUnresolvableReferences

### ISSUE THREAD

**Issue by simon-p-r** [zaggino/z-schema#78]
Hi again

What does this option do?  I have approx 40 separate schema files that I need to use $ref to point from one file to the other.  Can I set this to true to help Me resolve issues with 'missingReferences'?  In version 2 this were resolved by validating definition schemas first and then compiling them separately but in version 3 you use the 'validateSchema' method to validate and compile the schemas.  From my understanding using id to reference other schemas only works with embedded schemas in same physical file.

**Comment by zaggino** [comment]
It'll cause you to get rid of `"UNRESOLVABLE_REFERENCE"` errors. You can't set this to true for any production use. You need to put those 40 schemas into one array and run the `validateSchema` method over that array.

**Comment by simon-p-r** [comment]
I have tried this but still getting errors, I presume the order of objects in array must be in the order required to resolve $ref?

**Comment by zaggino** [comment]
Nope, the validator will resolve the order itself, so that's not an issue. But there might be issues when schemaA depends on schemaB and schemaB depends on schemaA (circular references). Do you have these schemas on GitHub or otherwise publicly available?

**Comment by simon-p-r** [comment]
Not public available, here is the schema I am pointing the 'contactLink' property to $ref, this is in file 'address.js'

```JS
schema:{
        properties:{

            description  : {type:'string'},
            buildingName : { type: 'string'},
            buildingNumber : { type: 'string'},
            county : { type: 'string'},
            country : { type: 'string',format:'sid'},
            isDefault : {type:'boolean'},
            isPreferred : {type:'boolean'},
            contactLink         :{$ref:'http://localhost:1234/contactLink'},
            locality : { type: 'string'},
            postCode : { type: 'string', format:'postcode'},
            postTown : { type: 'string'},
            thoroughfare : { type: 'string'},
            contactType : {type:'string',format:'lookup',lutype:'contact'},
            unitName : { type: 'string'},
        },
        title: 'definition schema for address',
        additionalProperties: false,
        type: 'object',
}

````

And here is the 'contactLink' schema which is a separate file called 'contactLink.js' in same directory

````JS
schema : {
        properties: {


            partyOID        : { type: 'string',format:'sid',collection:'party'},
            contactType     : {type:'string',format:'lookup',lutype:'contactType'}

        },
        title: 'definition schema for contactLink',
        additionalProperties: false,
        type: 'object',
    }

**Comment by zaggino** [comment]
You need to put `id: http://localhost:1234/contactLink` into the contactLink schema root, validator has no idea that the schema is in the same directory because it doesn't handle schema loading by itself.

**Comment by simon-p-r** [comment]
Sorry this doesn't work, it still returns with _$missingReferences value as 
````JS
[ { ref: 'http://localhost:1234/contactLink',
    key: '$ref',
    obj: 
     { '$ref': 'http://localhost:1234/contactLink',
       '__$refResolved': undefined },
    path: [ 'properties', 'contactLink' ] } ]

**Comment by zaggino** [comment]
Please, submit a full test scenario here, but I'm quite sure the first line shouldn't be:
`[ { ref: 'http://localhost:1234/contactLink',` but `[ { id: 'http://localhost:1234/contactLink',`

**Comment by simon-p-r** [comment]
Excellent that has worked, thank you for your help!
