### ISSUE TITLE
noExtraKeywords for object, not schema?

### ISSUE THREAD

**Issue by braco** [zaggino/z-schema#80]
I assumed "noExtraKeywords" was for the object to be validated. That is to say, throw an error when encountering any keys in the target object that aren't defined in the schema. This would make sure no keys were falling through the cracks.

This is not currently possible, correct?

A related feature would be to automatically remove/clean any unknown properties. lx-valid does this.

Maybe the config object should be namespaced:
```
config:
     schema:
            options....
     validation:
            options....
```
or separated completely:
```
validator = new zSchema.validator(schema config)
validator.validate(object config, object)
```

**Comment by zaggino** [comment]
`noExtraKeywords` is for schema and this is clearly stated in readme: https://github.com/zaggino/z-schema#noextrakeywords

for objects that are validated, there're keywords `additionalProperties: false` and `additionalItems: false` which are defined in JSON schema specification, you can set `forceAdditional: true` to be required to specify them in your schemas or you can use https://github.com/zaggino/z-schema#assumeadditional option

**Comment by braco** [comment]
So what combination of those two config items is "throw error when encountering unknown keys in target object"? I couldn't seem to get that to work.

**Comment by zaggino** [comment]
Please give a sample of the scenario where you expect the error - sample schema and sample object, thanks.

**Comment by braco** [comment]
object:
```
{
   foo: "this property should exist",
   bar: "this property should not exist"
}
```
schema:
```
{
  type: "object",
  properties: {
    foo: {
      type: "string"
    }
  }
}
```

The existence of "bar" should throw an error.

So just this type of scenario, but with many nested objects.

**Comment by zaggino** [comment]
Two options, create validator like this:
```
var validator = new ZSchema({
    assumeAdditional: true,
    noExtraKeywords: true
});
```
Or fix your schema with `additionalProperties` like this:
```
var schema = {
  type: "object",
  additionalProperties: false,
  properties: {
    foo: {
      type: "string"
    }
  }
};
```
and use validator like this:
```
var validator = new ZSchema({
    forceAdditional: true,
    noExtraKeywords: true
});
```
