### ISSUE TITLE
Error description inconsistencies

### ISSUE THREAD

**Issue by whitlockjc** [zaggino/z-schema#83]
I just recently updated to `3.3.2` from `3.2.0` and a number of my tests were failing due to changes in the schema validation error descriptions.  Here are a few examples:

* `Additional properties not allowed: extra` => `Additional properties not allowed: ["extra"]`
* `Missing required property: paths` => `Missing required property: "paths"`
* `Expected type string but found type boolean` => `Expected type "string" but found type "boolean"`

I'm sure there are more but in my local tests do not test all of Z-Schema.  Why the sudden use of `"` when referring to property names?  _(Not a big deal, just wondering if there was something to it.)_

When I looked around more, there are other places where you surround the property name with `'` instead of the `"` seen in so many other places.  Here is an example:

* `Data does not match any schemas from 'oneOf'`

It seems there is an inconsistency here as some places `'` is used, other places `"` is used.  Thoughts?

**Comment by zaggino** [comment]
That will be this commit: https://github.com/zaggino/z-schema/commit/2fd2f39fe6e4199b51f385963dff73ad53f56452

Because before this, sometimes you'd get `[object Object]` in the errors.

Didn't realize the consequences and this should be reverted (fixed a better way).

**Comment by zaggino** [comment]
@whitlockjc Fixed in `3.3.3`, maybe you can submit some of your tests for this to the repo so this doesn't break again without knowing about it.

**Comment by whitlockjc** [comment]
It shouldn't be necessary but I'll get back to you.  I don't mind my tests failing due to message/structure changes but it was when fixing them that I realized there were a number of different ways to mentions message properties in messages.  That's the only reason I brought it up, the inconsistency, not because I had to fix the tests.  ;)
