### ISSUE TITLE
z-schema is causing side effects on the schema (altering it) when run against the official JSON-schema test suite

### ISSUE THREAD

**Issue by Muscula** [zaggino/z-schema#85]
I've generated a report of what tests in the [official JSON-schema test suite](https://github.com/json-schema/JSON-Schema-Test-Suite) cause z-schema to alter (mutate) the schema object passed to z-schema:

https://github.com/Muscula/json-schema-benchmark/blob/master/reports/z-schema-side-effects.md

**Comment by zaggino** [comment]
Yes, that's a normal behaviour for z-schema. For testing purposes, just clone the schema for each validator separately: https://github.com/zaggino/z-schema/blob/master/benchmark/tester.js#L44-L46

**Comment by Muscula** [comment]
Ok. I would personally not like my validator to mutate the schema I pass into it. But it's up to you of corse.

**Comment by zaggino** [comment]
This should be fixable, I'll look into it and let you know.

**Comment by Muscula** [comment]
Cool :-)

**Comment by Muscula** [comment]
I just added a lot more detail to the side effects error report so it's easy for you to see what's going on and reproduce it:
https://github.com/Muscula/json-schema-benchmark/blob/master/reports/z-schema-side-effects.md

**Comment by zaggino** [comment]
How can I run the report myself if I clone your repo?

**Comment by Muscula** [comment]
It's quite simple:
```shell
npm install
node .
```
This will re-generate all the .md files, including the side effects reports. This includes the benchmark, so it takes a minute or two to run.
And note. If you get to zero side-effects, currently the old side-effects report is not deleted. So you need to look in README.md and see if your side-effects are zero.

**Comment by Muscula** [comment]
I just did an update, so now the old reports are deleted. so you file `reports/z-schema-side-effects.md` should disappear when you have no side-effects.

**Comment by zaggino** [comment]
This issue should be fixed in latest 3.4.0

**Comment by Muscula** [comment]
Great. My tests say the problem is gone.
