### ISSUE TITLE
Unresolvable reference for `$schema`

### ISSUE THREAD

**Issue by MattiSG** [zaggino/z-schema#88]
$ z-schema deleted-datasets.schema.json
	[ { code: 'UNRESOLVABLE_REFERENCE',
	    params: [ 'http://json-schema.org/draft-04/schema#' ],
	    message: 'Reference could not be resolved: http://json-schema.org/draft-04/schema#',
	    path: '#/' } ]
	schema validation failed

With the input file being [`deleted-datasets.schema.json`](https://github.com/etalab/deleted-datasets-schema/blob/0d14fb826b21359b907a0edddb35979e1861d0ad/deleted-datasets.schema.json), which has:

```json
"$schema": "http://json-schema.org/draft-04/schema#"
```

I don't think this error is legit.

**Comment by zaggino** [comment]
Fixed - `npm update -g z-schema`
```
$ z-schema deleted-datasets.schema.json
request: http://json-schema.org/draft-04/schema - 200
schema validation passed
```

**Comment by zaggino** [comment]
The error was legit, CLI wasn't downloading remote references that should be used for validation but I've fixed that.

**Comment by MattiSG** [comment]
Nailed it, thanks! Congratulations, `z-schema` is now officially [used](https://github.com/etalab/deleted-datasets-schema/blob/master/package.json#L3) by the French government  ;)

**Comment by zaggino** [comment]
Nice :) Let me know if you'll need any more features.
Btw I see that you did
`
z-schema deleted-datasets.schema.json && z-schema deleted-datasets.schema.json example.json
`
but you only really have to do
`
z-schema deleted-datasets.schema.json example.json
`
Schema is always validated, whether you pass any json file or not as following arguments.

**Comment by MattiSG** [comment]
> Schema is always validated, whether you pass any json file or not as following arguments.

Mmh… I see that, but I need this behaviour to be explicitly documented to use it.

So hey, I did #89  ;)
