### ISSUE TITLE
noExtraKeywords doesn't catch bad keywords in schema with parent

### ISSUE THREAD

**Issue by bvitale** [zaggino/z-schema#92]
I see that this is explicit in the source of ZSchema, but the following minimal schema with a parent $schema of JSON Schema itself does not report the 'foo' keyword:

```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Test",
  "foo":"bob"
}
```

```
./node_modules/z-schema/bin/z-schema --noExtraKeywords min.jsonschema
request: http://json-schema.org/draft-04/schema - 200
schema validation passed
```

Whereas with no $schema, it reports it. 

If JSON Schema is the default parent, shouldn't these behave the same?

**Comment by zaggino** [comment]
In this case, your schema is validated against parent schema (`http://json-schema.org/draft-04/schema`) and the parent schema specifies, that the extra keywords are allowed.
