### ISSUE TITLE
Cache problem

### ISSUE THREAD

**Issue by simon-p-r** [zaggino/z-schema#95]
Hi

Can you explain how the cache is created?  I am migrating some working code and because the cache is not being created when I use the 'validateSchema' method it returns errors.  The objects are being stored in the 'referenceCache' array. 

Thanks

**Comment by simon-p-r** [comment]
I had to deep clone the cache from another object before I called the 'validateSchema' method, now everything is working as to be expected.

**Comment by zaggino** [comment]
`referenceCache` is there so we don't do any modifications of the original objects

I didn't really understood what you're trying to do from your issue, but if you need any help, let me know. A code scenario would be useful.

**Comment by simon-p-r** [comment]
Basically the issue was I was setting my references with any object created with a constructor and then using another object created by another constructor to call 'validateSchema' which meant the value of the 'this' property was different hence no cache in my objects properties.  My mistake as still very new to programming.  What is the change in the latest version?

**Comment by zaggino** [comment]
latest version has improvements for this issue: https://github.com/zaggino/z-schema/issues/94
