### ISSUE TITLE
Email format validation false negatives

### ISSUE THREAD

**Issue by Sencerd** [zaggino/z-schema#96]
The email validation regex used for the email format checking is incorrect, and will fail for valid email addresses. For example, anything that includes an underscore before a period will fail (eg: my_email@gmail.com)

https://github.com/chriso/validator.js has a very good email regex, including it as a dependency may be a little OTT, but the regex could be used in place of the existing one, thoughts?

**Comment by zaggino** [comment]
that's definitely a bug

i'll take a look at the https://github.com/chriso/validator.js and consider making it a dependency if browserify is able to handle all this fine (i've had issues with it before)

**Comment by zaggino** [comment]
Should be fixed in `3.6.1`, let me know if you'll have any more issues.

**Comment by Sencerd** [comment]
That's perfect, thank you for the speedy fix!
