### ISSUE TITLE
Resolving references when using Node.JS library

### ISSUE THREAD

**Issue by joetconcur** [zaggino/z-schema#99]
I really like the enhancement you added to the CLI to enable local file reference resolution. It works perfectly. Is it possible to have the same capability when validate in NodeJS.

My schema has references to another schema file in the same directory, like
`{ "$ref": "anotherSchema.json#/definitions/anotherType" }`

When I tried to do validate in js, all the references could not be resolved.
```
{ code: 'UNRESOLVABLE_REFERENCE',
    params: [ 'anotherSchema.json#/definitions/anotherType' ],
    message: 'Reference could not be resolved: anotherSchema.json#/definitions/anotherType',
    path: '...' }
```
Below is my code:

```javascript
var url = require('url');
var fs = require('fs');
var ZSchema = require('z-schema');
var validator = new ZSchema({
    breakOnFirstError: false
});

var pathToSchemaFolder = __dirname + '/../schema/';
var pathToJsonFolder = __dirname + '/../json/';

var schemaText = fs.readFileSync(pathToSchemaFolder + 'schema.json', { encoding: "utf8" });
var schema = JSON.parse(schemaText);

var jsonText = fs.readFileSync(pathToJsonFolder + 'sample.json', { encoding: "utf8" });
var json = JSON.parse(jsonText);

var valid = validator.validate(json, schema);
console.log(valid);
console.log(validator.getLastErrors());
```

Thanks.

**Comment by zaggino** [comment]
When using `node-js` library, the proper loading of all the schemas is up to you, because every project can have this implemented differently.

This is how CLI does it: https://github.com/zaggino/z-schema/blob/master/bin/z-schema#L65-L128
Basically it tries to validate the schemas and if gets any unresolved ones, loads them and runs the validation again. This is one option.

Other option is, what I do with my servers, that I use https://www.npmjs.com/package/glob to load all files like this (see code below) and fill them all into `z-schema` with `schemaValidator.validateSchema(schemaArray)`

```
let readFileSync = exports.readFileSync = function (filePath) {
  return fs.readFileSync(filePath, {encoding: 'utf8'});
};

let readJsonSync = exports.readJsonSync = function (filePath) {
  try {
    return JSON.parse(readFileSync(filePath));
  } catch (e) {
    throw new Error(e.message + ' - failed to parse ' + filePath);
  }
};

exports.getSchemasFromDirectory = function (schemasDirPath) {
  return glob.sync('./**/*.schema.json', {
    cwd: schemasDirPath
  }).map(function (fileName) {
    return readJsonSync(path.resolve(schemasDirPath, fileName));
  });
};
```

**Comment by joetconcur** [comment]
Ah... I see what I was missing now. Before calling validate, I have to load all the references manually using `validator.setRemoteReference(url, reference)`.

Now what I don't understand though is why `http://json-schema.org/draft-04/schema` is not resolved automatically by z-schema? In all my schemas, I have `"$schema": "http://json-schema.org/draft-04/schema#"` as the first line. I found out that I had to do a request and do setRemoteReference for this url manually along with other custom references, otherwise I would get unresolved reference error. Isn't this line a standard in json schemas? I am new to json schema here.

**Comment by zaggino** [comment]
`http://json-schema.org/draft-04/schema` is just one of standard schemas, other one is `http://json-schema.org/draft-04/hyper-schema` and also it's completely valid to define your own if you want; or don't use `$schema` at all ...

**Comment by joetconcur** [comment]
I see. Thanks for taking the time to explain.
Since there are just 2 *standard* schemas - `http://json-schema.org/draft-04/schema` and `http://json-schema.org/draft-04/hyper-schema`, IMHO, they should be an exception, i.e., the validator should have knowledge of the two and not require clients to manually `setRemoteReference` for them. Just my 2 cents.

**Comment by zaggino** [comment]
Do you mean exception as that z-schema should do what? Ignore them or have them downloaded together with the library?

**Comment by joetconcur** [comment]
If the data from those url is not used in the validation, ignore them. If it is used, have them downloaded together with the library.

**Comment by zaggino** [comment]
Ok, I can bundle them with the next version of `z-schema`

**Comment by zaggino** [comment]
@joetconcur these schemas are now bundled with `z-schema@3.9.0`

**Comment by joetconcur** [comment]
Awesome! It works perfectly. Thanks!
